



```{r}
library(ggplot2)
library(viridis)
library(sf)
library(tidyr)
library(latex2exp)
```



```{r}
br<-st_read("r1.shp")

br <- br |>
  drop_na(Riqueza)
  #dplyr::filter(!Riqueza %in% NA)

br2 <- st_read("Costello_equalarea.shp")

```



```{r}

# pdf("fig1.pdf", height = 4000, width = 7000)

obs <- ggplot() +
  geom_sf(data = br2) +
  geom_sf(data = br,aes(fill = log10(Riqueza), lwd = NA)) +
#  scale_fill_viridis() +
  scale_fill_viridis(option = "B") +
# ggtitle("Observed Richness (log10)") +
  theme_bw()+
  labs(fill = "Observed\nrichness") +
  theme(axis.text.x =  element_blank(),
        axis.line = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()) +
  theme(
#    panel.background = element_blank(),  # Sin fondo en el panel interior
    panel.grid.major = element_blank(),  # Líneas exteriores sólidas y negras
    panel.border = element_blank(),
    panel.grid.minor = element_blank()) +
  theme(legend.position = "right", 
        legend.justification = "center",
        legend.title = element_blank()
        )

obs
```



```{r}
So <- ggplot()+ geom_histogram(data=br, aes(x=Riqueza))+ 
  xlab(TeX("S$_{obs}$"))
lSo <- ggplot()+ geom_histogram(data=br, aes(x=log10(Riqueza)))+
  xlab(TeX("log$_{10}(S_{obs})$"))
S2o <- ggplot()+ geom_histogram(data=br, aes(x=Riqueza2))+
  xlab(TeX("S$_{est}$"))
lS2o <- ggplot()+ geom_histogram(data=br, aes(x=log10(Riqueza2))) +
  xlab(TeX("log$_{10}(S_{est})$"))


ggpubr::ggarrange(So,lSo,S2o,lS2o,ncol=4)


obs
#ggsave("Fig1.pdf")

```




# Figure 2

```{r}

# br<-st_read("r1.shp")
br <- br |>
  drop_na(Riqueza2)

#br2 <- st_read("Costello_equalarea.shp")
# png("fig2.png", height = 4000, width = 7000, res = 800)
```





```{r}
est <- ggplot()+
        geom_sf(data = br2) +
        geom_sf(data = br,aes(fill = log10(Riqueza2), lwd = NA)) +
        scale_fill_viridis(option = "B") +
        theme_bw() +
 #       ggtitle("Estimated Richness (log10)") +
        labs(fill = "Estimated\nrichness") +
        theme(axis.text.x =  element_blank(),
                axis.ticks = element_blank(),
                axis.text.y = element_blank() ) +
        theme(legend.position = "right",
        legend.title = element_blank(),
        legend.justification = "center") +  
        theme(
          panel.background = element_blank(),  # Sin fondo en el panel interior
          panel.grid.major = element_blank(),  # Líneas exteriores sólidas y negras
          panel.border = element_blank(),
          panel.grid.minor = element_blank()  # Sin líneas interiores)
          )
est
```



# Figure 3
## SRI Values

```{r}
#br<-st_read("capas/r1.shp")

br<- br |>
  drop_na(Coef_1)
#br2 <- st_read("shape/Costello_equalarea.shp")
```



```{r}
# png("fig3.png", height = 4000, width = 7000, res = 800)

SRI <- ggplot()+
  geom_sf(data = br2)+
  geom_sf(data = br,aes(fill = Coef_1, lwd = NA))+
  scale_fill_viridis(option = "D") +
  theme_bw()+
  labs(fill = "SRI") +
#  ggtitle("SRI") +
  theme(axis.text.x =  element_blank(),
          axis.ticks = element_blank(),
          axis.text.y = element_blank())+
  theme(legend.position = "right",
        legend.title = element_blank(),
        legend.justification = "center")+  
  theme(
    panel.background = element_blank(),  # Sin fondo en el panel interior
    panel.grid.major = element_blank(),  # Líneas exteriores sólidas y negras
    panel.border = element_blank(),
    panel.grid.minor = element_blank())  # Sin líneas interiores)

SRI
```


```{r}
library(ggpubr)
# ggarrange(SRI,
#           ggarrange(obs, est, labels = c("B", "C"), ncol = 2 ),
#           nrow = 2, labels = "A", widths = c(4,0.5)
#           )

ggarrange(SRI,obs, est, 
          nrow = 3, labels = LETTERS[1:3], align = "v"#, widths = c(4,0.5)
          )
#ggsave("maps_Appendix.pdf",width=20,height = 25,units="cm")
```

## Mapa de diferencias

restemos el `Estimado` - `observado`


```{r}
br$diferencia <- log10(br$Riqueza2 - br$Riqueza + 1)
diferencia <- ggplot()+
  geom_sf(data = br2)+
  geom_sf(data = br,aes(fill = diferencia, lwd = NA))+
  scale_fill_viridis(option = "D") +
  theme_bw()+
#  labs(fill = "Estimated - Observed Richness") +
#  ggtitle("Richness Difference (Log10)") +
  theme(axis.text.x =  element_blank(),
          axis.ticks = element_blank(),
          axis.text.y = element_blank())+
  theme(legend.position = "right",
        legend.title = element_blank(),
        legend.justification = "center")+  
  theme(
    panel.background = element_blank(),  # Sin fondo en el panel interior
    panel.grid.major = element_blank(),  # Líneas exteriores sólidas y negras
    panel.border = element_blank(),
    panel.grid.minor = element_blank())  # Sin líneas interiores)

diferencia
```

Ahora en una figura de 2x2

```{r}
ggarrange(SRI,obs, est, diferencia,
          nrow = 2,ncol=2, labels = LETTERS[1:4]#, align = "v"#, widths = c(4,0.5)
          )
ggsave("maps_Appendix_2.pdf",width=25,height = 15,units="cm")

```


```{r}
library(cowplot)


ggarrange(obs,est,ncol = 2)

kmeans(br$Riqueza)

```

```{r}
sri.hist <- ggplot(data=br[which(br$Coef_1>0),],aes(x=Coef_1))+
  geom_histogram(bins=20,fill="steelblue4")+
  xlab("SRI") #+
#  geom_vline(aes(xintercept = 0.6), colour="black") + 
#  geom_vline(aes(xintercept = 0.85), colour="black")

sri.hist + annotate("text",x=.5,y=1200,label= "L",fontface=2,size=18/.pt) +
  theme_minimal(base_size = 14) +
  annotate("text",x=.62,y=1200,label= "M",fontface=2,size=18/.pt) +
annotate("text",x=.87,y=1200,label= "H",fontface=2,size=18/.pt) +
  ylab("frequency") +
  annotate("rect",xmin = .45,xmax = .6,ymin = 0,ymax = 1400,alpha=.1)+
  annotate("rect",xmin = .6,xmax = .85,ymin = 0,ymax = 1400,alpha=.2)+
  annotate("segment",x=.6,xend=.6,y=0,yend=1400,color="blue4")+
  annotate("rect",xmin = .85,xmax = 1.0,ymin = 0,ymax = 1400,alpha=.1)+
  annotate("segment",x=.85,xend=.85,y=0,yend=1400,color="blue4")+
  ylim(0,1400)

ggsave("SRI_hist.pdf",width=15,height = 10,units="cm")
  
```

